const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const pad=n=>String(n).padStart(2,'0');
let app='clock',streak=0;

// Clock tool
const clock=$('#clock'),feedback=$('#feedback'),submitBtn=$('#submitBtn');
let mode='read',question=0,score=0,group=[],current,handTime,chosenPeriod='上午',selectedHand='hour',groupComplete=false;
const format=t=>`${pad(t.h)}:${pad(t.m)}`;
const randomTime12=()=>({h:Math.floor(Math.random()*12)+1,m:Math.floor(Math.random()*12)*5});
const randomTime24=()=>({h:Math.floor(Math.random()*24),m:Math.floor(Math.random()*12)*5});
function randomCalc(){const start={h:Math.floor(Math.random()*13)+6,m:Math.floor(Math.random()*12)*5},answer=(Math.floor(Math.random()*43)+6)*5,total=start.h*60+start.m+answer;return total>1435?randomCalc():{start,end:{h:Math.floor(total/60),m:total%60},answer}}
function makeClockGroup(){const seen=new Set();group=[];while(group.length<5){const t=mode==='calc'?randomCalc():mode==='convert'?randomTime24():randomTime12(),key=mode==='calc'?`${format(t.start)}-${format(t.end)}`:format(t);if(!seen.has(key)){seen.add(key);group.push(t)}}}
function drawClock(t){clock.innerHTML='';clock.classList.toggle('readonly',mode==='read');for(let i=0;i<12;i++){const x=document.createElement('i');x.className='tick '+(i%3===0?'major':'');x.style.transform=`translate(-50%,-100%) rotate(${i*30}deg)`;clock.append(x)}for(let n=1;n<=12;n++){const a=n*30*Math.PI/180,x=document.createElement('span');x.className='number';x.textContent=n;x.style.left=`${50+39*Math.sin(a)}%`;x.style.top=`${50-39*Math.cos(a)}%`;clock.append(x)}addHand('hour-hand',(t.h%12)*30+t.m*.5);addHand('minute-hand',t.m*6);const dot=document.createElement('i');dot.className='center-dot';clock.append(dot);if(mode==='set')clock.addEventListener('pointerdown',startDrag)}
function addHand(cls,deg){const x=document.createElement('i');x.className='hand '+cls;x.style.transform=`rotate(${deg}deg)`;clock.append(x)}
function startDrag(e){e.preventDefault();const move=ev=>{const r=clock.getBoundingClientRect(),a=(Math.atan2(ev.clientY-r.top-r.height/2,ev.clientX-r.left-r.width/2)*180/Math.PI+450)%360;if(selectedHand==='minute')handTime.m=Math.round(a/30)*5%60;else{let h=Math.round((a-handTime.m*.5)/30)%12;handTime.h=h||12}drawClock(handTime)},stop=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop)};move(e);window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop)}
function time12(t){return {period:t.h<12?'上午':'下午',h:t.h%12||12,m:t.m}}
function loadConvert(){current.direction=Math.random()<.5?'to24':'to12';const shown=current.direction==='to24'?`${time12(current).period} ${format(time12(current))}`:format(current);$('#questionTitle').textContent=current.direction==='to24'?`请把 ${shown} 换成 24 小时制：`:`请把 ${shown} 换成 12 小时制：`;$('#convertHint').textContent=current.direction==='to24'?'请输入 24 小时制时间。':'请输入 12 小时制时间，并选择上午或下午。';$('#periodRow').classList.toggle('hidden',current.direction==='to24');$('#convertHour').value=$('#convertMinute').value='';chosenPeriod='上午'}
function loadClock(){current=group[question];handTime=mode==='set'?{h:12,m:0}:{...current};groupComplete=false;$('#clockWrap').classList.toggle('hidden',mode==='calc'||mode==='convert');$('#handControls').classList.toggle('hidden',mode!=='set');if(mode==='read'||mode==='set')drawClock(mode==='read'?current:handTime);if(mode==='set')$('#targetTime').textContent=format(current);if(mode==='convert')loadConvert();if(mode==='calc'){ $('#questionTitle').textContent='小火车从起点开到终点，一共用了多长时间？';$('#calcStart').textContent=format(current.start);$('#calcEnd').textContent=format(current.end);['#calcEndHour','#calcEndMinute','#calcStartHour','#calcStartMinute','#calcDurationHour','#calcDurationMinute'].forEach(x=>$(x).value='') }$('#progressText').textContent=`${question+1} / 5`;$('#progressBar').style.width=`${(question+1)*20}%`;feedback.textContent='';feedback.className='feedback';$('#hourInput').value=$('#minuteInput').value=''}
function clockCorrect(){if(mode==='read')return +$('#hourInput').value===current.h&&+$('#minuteInput').value===current.m;if(mode==='set')return handTime.h===current.h&&handTime.m===current.m;if(mode==='convert'){const h=+$('#convertHour').value,m=+$('#convertMinute').value;if(current.direction==='to24')return h===current.h&&m===current.m;const a=time12(current);return h===a.h&&m===a.m&&chosenPeriod===a.period}return +$('#calcEndHour').value===current.end.h&&+$('#calcEndMinute').value===current.end.m&&+$('#calcStartHour').value===current.start.h&&+$('#calcStartMinute').value===current.start.m&&+$('#calcDurationHour').value===Math.floor(current.answer/60)&&+$('#calcDurationMinute').value===current.answer%60}
function selectClockMode(next){mode=next;question=score=0;makeClockGroup();$$('.clock-modes .mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));const names={read:'看钟写时间',set:'拨钟调时间',convert:'12 / 24 小时制',calc:'时间竖式计算'};$('#modeTag').textContent=names[mode];$('#readAnswer').classList.toggle('hidden',mode!=='read');$('#setAnswer').classList.toggle('hidden',mode!=='set');$('#convertAnswer').classList.toggle('hidden',mode!=='convert');$('#calcAnswer').classList.toggle('hidden',mode!=='calc');loadClock()}
submitBtn.onclick=()=>{if(groupComplete)return;const ok=clockCorrect();streak=ok?streak+1:0;$('#streakCount').textContent=streak;feedback.textContent=ok?'答对啦！你真是钟表小达人 🎉':'再想一想，仔细看看钟面哦。';feedback.className=`feedback ${ok?'good':'bad'}`;submitBtn.disabled=true;setTimeout(()=>{if(question===4){groupComplete=true;feedback.textContent=`本组完成！答对 ${score+(ok?1:0)} / 5 题。`;submitBtn.disabled=false;return}score+=ok?1:0;question++;submitBtn.disabled=false;loadClock()},900)};
$$('.clock-modes .mode').forEach(x=>x.onclick=()=>selectClockMode(x.dataset.mode));$$('.period').forEach(x=>x.onclick=()=>{chosenPeriod=x.dataset.period;$$('.period').forEach(y=>y.classList.toggle('active',x===y))});$$('.hand-control').forEach(x=>x.onclick=()=>{selectedHand=x.dataset.hand;$$('.hand-control').forEach(y=>y.classList.toggle('active',x===y))});

// Fraction tool
let fractionMode='read',fractionQuestion=0,fractionScore=0,fractionGroup=[],fractionCurrent,cutCount=0,plate=new Set(),fractionComplete=false,cutLines=[],isCutting=false,tempCutLine=null,drawingCut=false;
function makeFractionGroup(){fractionGroup=[];while(fractionGroup.length<5){const d=[2,3,4,5,6,8][Math.floor(Math.random()*6)],n=Math.floor(Math.random()*d)+1;if(!fractionGroup.some(x=>x.d===d&&x.n===n))fractionGroup.push({n,d})}}
function drawPizza(parts,selected=0,interactive=false){const pizza=$('#pizza'),ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg'),c=150,r=150;svg.setAttribute('viewBox','0 0 300 300');pizza.innerHTML='';pizza.classList.toggle('cutting',isCutting);if(parts===1){const whole=document.createElementNS(ns,'circle');whole.setAttribute('cx',c);whole.setAttribute('cy',c);whole.setAttribute('r',r);whole.setAttribute('class','pizza-slice');svg.append(whole);[...cutLines,tempCutLine].filter(Boolean).forEach(cut=>{const line=document.createElementNS(ns,'line');line.setAttribute('x1',cut.x1);line.setAttribute('y1',cut.y1);line.setAttribute('x2',cut.x2);line.setAttribute('y2',cut.y2);line.setAttribute('class','pizza-cut-line');svg.append(line)})}else for(let i=0;i<parts;i++){const a1=i*2*Math.PI/parts,a2=(i+1)*2*Math.PI/parts,x1=c+Math.sin(a1)*r,y1=c-Math.cos(a1)*r,x2=c+Math.sin(a2)*r,y2=c-Math.cos(a2)*r,path=document.createElementNS(ns,'path');path.setAttribute('d',`M ${c} ${c} L ${x1.toFixed(2)} ${y1.toFixed(2)} A ${r} ${r} 0 ${parts>2?0:1} 1 ${x2.toFixed(2)} ${y2.toFixed(2)} Z`);path.setAttribute('class',`pizza-slice${fractionMode==='read'&&i<selected?' taken':''}${fractionMode==='make'&&plate.has(i)?' on-plate':''}`);if(interactive){path.dataset.slice=i;path.setAttribute('role','button');path.setAttribute('tabindex','0');path.setAttribute('aria-label',`第 ${i+1} 块披萨，点击放入或取出盘子`)}svg.append(path)}pizza.append(svg)}
function togglePizzaSlice(slice){if(cutCount<neededCuts())return;plate.has(slice)?plate.delete(slice):plate.add(slice);drawPizza(fractionCurrent.d,0,true);updateMakeStatus()}
function pizzaPoint(e){const rect=$('#pizza').getBoundingClientRect();return {x:(e.clientX-rect.left)*300/rect.width,y:(e.clientY-rect.top)*300/rect.height}}
const neededCuts=()=>fractionCurrent.d%2===0?fractionCurrent.d/2:fractionCurrent.d;
const nearEdge=p=>Math.hypot(p.x-150,p.y-150)>112;
const nearCenter=p=>Math.hypot(p.x-150,p.y-150)<48;
const lineNearCenter=cut=>{const dx=cut.x2-cut.x1,dy=cut.y2-cut.y1;return Math.abs(dx*(150-cut.y1)-dy*(150-cut.x1))/Math.hypot(dx,dy)<35};
const cutGuide=()=>fractionCurrent.d%2===0?'从披萨一侧边缘划到另一侧边缘，线要经过中间。':'从披萨中心向边缘划出放射线。';
const angleGap=(a,b,cycle)=>{const gap=Math.abs(a-b)%cycle;return Math.min(gap,cycle-gap)};
function equalShareAngle(cut){const even=fractionCurrent.d%2===0,raw=Math.atan2(cut.y2-cut.y1,cut.x2-cut.x1),cycle=even?Math.PI:Math.PI*2,angle=(raw+cycle)%cycle;if(!cutLines.length)return true;const baseRaw=Math.atan2(cutLines[0].y2-cutLines[0].y1,cutLines[0].x2-cutLines[0].x1),base=(baseRaw+cycle)%cycle,step=cycle/neededCuts();return Array.from({length:neededCuts()},(_,i)=>(base+i*step)%cycle).some(expected=>angleGap(angle,expected,cycle)<.46)&&!cutLines.some(line=>{const a=(Math.atan2(line.y2-line.y1,line.x2-line.x1)+cycle)%cycle;return angleGap(angle,a,cycle)<.32})}
$('#pizza').addEventListener('pointerdown',e=>{if(!isCutting||cutLines.length>=neededCuts())return;e.preventDefault();const p=pizzaPoint(e);drawingCut=true;tempCutLine={x1:p.x,y1:p.y,x2:p.x,y2:p.y};$('#pizza').setPointerCapture?.(e.pointerId);drawPizza(1)});
$('#pizza').addEventListener('pointermove',e=>{if(!drawingCut)return;const p=pizzaPoint(e);tempCutLine={...tempCutLine,x2:p.x,y2:p.y};drawPizza(1)});
$('#pizza').addEventListener('pointerup',e=>{if(!drawingCut)return;drawingCut=false;const end=pizzaPoint(e),cut={...tempCutLine,x2:end.x,y2:end.y},start={x:cut.x1,y:cut.y1};tempCutLine=null;const shaped=fractionCurrent.d%2===0?nearEdge(start)&&nearEdge(end)&&Math.hypot(cut.x2-cut.x1,cut.y2-cut.y1)>190&&lineNearCenter(cut):(nearCenter(start)&&nearEdge(end)||nearCenter(end)&&nearEdge(start)),valid=shaped&&equalShareAngle(cut);if(valid){cutLines.push(cut);cutCount=cutLines.length;if(cutCount>=neededCuts()){isCutting=false;$('#pizzaNote').textContent='披萨切好了！点击披萨块放入盘子';$('#makeHint').textContent='现在点击披萨块，把需要的份数放进盘子。';$('#cutPizzaBtn').textContent='✓ 已切好'}else $('#makeHint').textContent=`很好！${cutGuide()} 还要 ${neededCuts()-cutCount} 刀。`}else $('#makeHint').textContent=shaped?'这条线和前面的切法太接近了，换个角度，切出一样大的份。':`这一刀不太像等分切法：${cutGuide()} 再试一次。`;drawPizza(cutCount>=neededCuts()?fractionCurrent.d:1,0,cutCount>=neededCuts());updateMakeStatus()});
$('#pizza').addEventListener('click',e=>{const slice=e.target.dataset.slice;if(slice!==undefined)togglePizzaSlice(Number(slice))});
$('#pizza').addEventListener('keydown',e=>{const slice=e.target.dataset.slice;if(slice!==undefined&&(e.key==='Enter'||e.key===' ')){e.preventDefault();togglePizzaSlice(Number(slice))}});
function updateMakeStatus(){$('#cutCount').textContent=`${cutCount} / ${fractionMode==='make'?neededCuts():0}`;$('#plateCount').textContent=plate.size}
function loadFraction(){fractionCurrent=fractionGroup[fractionQuestion];fractionComplete=false;plate.clear();cutCount=0;cutLines=[];isCutting=false;tempCutLine=null;$('#fractionProgressText').textContent=`${fractionQuestion+1} / 5`;$('#fractionProgressBar').style.width=`${(fractionQuestion+1)*20}%`;$('#fractionFeedback').textContent='';$('#fractionFeedback').className='feedback';$('#numeratorInput').value=$('#denominatorInput').value='';if(fractionMode==='read'){ $('#fractionTitle').textContent='披萨被平均分成几份？取了几份？';$('#pizzaNote').textContent='橙色的是取出的披萨';drawPizza(fractionCurrent.d,fractionCurrent.n) }else{$('#fractionTitle').textContent='按照分数，把正确数量的披萨放进盘子！';$('#targetNumerator').textContent=fractionCurrent.n;$('#targetDenominator').textContent=fractionCurrent.d;$('#pizzaNote').textContent=cutGuide();$('#makeHint').textContent=`点“开始切披萨”后，${cutGuide()}`;$('#cutPizzaBtn').textContent='✂️ 开始切披萨';drawPizza(1);updateMakeStatus()}}
function fractionCorrect(){return fractionMode==='read'?+$('#numeratorInput').value===fractionCurrent.n&&+$('#denominatorInput').value===fractionCurrent.d:cutCount===neededCuts()&&plate.size===fractionCurrent.n}
function selectFractionMode(next){fractionMode=next;fractionQuestion=fractionScore=0;makeFractionGroup();$$('.fraction-modes .mode').forEach(x=>x.classList.toggle('active',x.dataset.fractionMode===next));$('#fractionModeTag').textContent=next==='read'?'分数的读取':'分数小厨师';$('#fractionReadAnswer').classList.toggle('hidden',next!=='read');$('#fractionMakeAnswer').classList.toggle('hidden',next!=='make');loadFraction()}
$('#cutPizzaBtn').onclick=()=>{if(cutCount>=neededCuts())return;isCutting=true;plate.clear();$('#pizzaNote').textContent=cutGuide();$('#makeHint').textContent=`需要切 ${neededCuts()} 刀；${cutGuide()}`;$('#cutPizzaBtn').textContent='✂️ 正在切披萨';drawPizza(1);updateMakeStatus()};$('#clearPlateBtn').onclick=()=>{plate.clear();cutCount=0;cutLines=[];isCutting=false;tempCutLine=null;$('#pizzaNote').textContent=cutGuide();$('#makeHint').textContent=`点“开始切披萨”后，${cutGuide()}`;$('#cutPizzaBtn').textContent='✂️ 开始切披萨';drawPizza(1);updateMakeStatus()};
$('#fractionSubmitBtn').onclick=()=>{if(fractionComplete)return;const ok=fractionCorrect();streak=ok?streak+1:0;$('#streakCount').textContent=streak;const f=$('#fractionFeedback');f.textContent=ok?'答对啦！披萨分得真棒 🎉':`再试试：答案是 ${fractionCurrent.n}/${fractionCurrent.d}。`;f.className=`feedback ${ok?'good':'bad'}`;$('#fractionSubmitBtn').disabled=true;setTimeout(()=>{if(fractionQuestion===4){fractionComplete=true;f.textContent=`本组完成！答对 ${fractionScore+(ok?1:0)} / 5 题。`;$('#fractionSubmitBtn').disabled=false;return}fractionScore+=ok?1:0;fractionQuestion++;$('#fractionSubmitBtn').disabled=false;loadFraction()},900)};
$$('.fraction-modes .mode').forEach(x=>x.onclick=()=>selectFractionMode(x.dataset.fractionMode));
$$('.nav-item').forEach(x=>x.onclick=()=>{app=x.dataset.app;$$('.nav-item').forEach(y=>y.classList.toggle('active',y===x));$('#clockApp').classList.toggle('hidden',app!=='clock');$('#fractionApp').classList.toggle('hidden',app!=='fraction')});$$('.restart-btn').forEach(x=>x.onclick=()=>{if(x.dataset.restart==='clock'){question=score=0;makeClockGroup();loadClock()}else{fractionQuestion=fractionScore=0;makeFractionGroup();loadFraction()}streak=0;$('#streakCount').textContent=0});
function launchFireworks(){const box=$('#fireworks'),colors=['#ff5d7a','#ffce55','#38b978','#3867f5','#a86df5','#ff9155'];for(let burst=0;burst<3;burst++){const x=22+Math.random()*56,y=7+Math.random()*20;for(let i=0;i<18;i++){const spark=document.createElement('i'),angle=Math.PI*2*i/18+Math.random()*.25,distance=42+Math.random()*82;spark.className='firework';spark.style.setProperty('--x',`${x}%`);spark.style.setProperty('--y',`${y}%`);spark.style.setProperty('--dx',`${Math.cos(angle)*distance}px`);spark.style.setProperty('--dy',`${Math.sin(angle)*distance}px`);spark.style.setProperty('--spark',colors[(i+burst)%colors.length]);spark.style.animationDelay=`${burst*.12}s`;box.append(spark);setTimeout(()=>spark.remove(),1200)}}
}
$('#submitBtn').addEventListener('click',()=>{if(!groupComplete&&clockCorrect())launchFireworks()});
$('#fractionSubmitBtn').addEventListener('click',()=>{if(!fractionComplete&&fractionCorrect())launchFireworks()});
function showSadMascot(){const mascot=$('#sadMascot');mascot.classList.remove('hidden');clearTimeout(showSadMascot.timer);showSadMascot.timer=setTimeout(()=>mascot.classList.add('hidden'),1000)}
$('#submitBtn').addEventListener('click',()=>{if(!groupComplete&&!clockCorrect())showSadMascot()});
$('#fractionSubmitBtn').addEventListener('click',()=>{if(!fractionComplete&&!fractionCorrect())showSadMascot()});
makeClockGroup();loadClock();makeFractionGroup();loadFraction();
