const $=s=>document.querySelector(s);
const clock=$('#clock'),feedback=$('#feedback'),submitBtn=$('#submitBtn');
let mode='read',question=0,score=0,streak=0,group=[],current,handTime,chosenPeriod='上午',groupComplete=false;
const pad=n=>String(n).padStart(2,'0');
const format=t=>`${pad(t.h)}:${pad(t.m)}`;
const randomTime12=()=>({h:Math.floor(Math.random()*12)+1,m:Math.floor(Math.random()*12)*5});
const randomTime24=()=>({h:Math.floor(Math.random()*24),m:Math.floor(Math.random()*12)*5});
function randomCalc(){const start={h:Math.floor(Math.random()*13)+6,m:Math.floor(Math.random()*12)*5};const difference=Math.floor(Math.random()*43+6)*5;const total=start.h*60+start.m+difference;if(total>1435)return randomCalc();return {start,end:{h:Math.floor(total/60),m:total%60},answer:difference}}
function makeGroup(){const seen=new Set();group=[];while(group.length<5){const t=mode==='calc'?randomCalc():mode==='convert'?randomTime24():randomTime12();const key=mode==='calc'?`${format(t.start)}-${format(t.end)}`:`${t.h}-${t.m}`;if(!seen.has(key)){seen.add(key);group.push(t)}}}
function drawClock(t){clock.innerHTML='';for(let i=0;i<12;i++){const x=document.createElement('i');x.className='tick '+(i%3===0?'major':'');x.style.transform=`translate(-50%,-100%) rotate(${i*30}deg)`;clock.append(x)}for(let n=1;n<=12;n++){const angle=n*30*Math.PI/180,x=document.createElement('span');x.className='number';x.textContent=n;x.style.left=`${50+39*Math.sin(angle)}%`;x.style.top=`${50-39*Math.cos(angle)}%`;clock.append(x)}addHand('hour-hand',(t.h%12)*30+t.m*.5);addHand('minute-hand',t.m*6);const dot=document.createElement('i');dot.className='center-dot';clock.append(dot);if(mode==='set'){clock.querySelectorAll('.hand').forEach(x=>x.addEventListener('pointerdown',startDrag));clock.addEventListener('pointerdown',pickMinute)}}
function addHand(cls,deg){const x=document.createElement('i');x.className='hand '+cls;x.style.transform=`rotate(${deg}deg)`;clock.append(x)}
function clockAngle(e){const r=clock.getBoundingClientRect();let a=Math.atan2(e.clientY-(r.top+r.height/2),e.clientX-(r.left+r.width/2))*180/Math.PI+90;return a<0?a+360:a}
function startDrag(e){e.stopPropagation();const minute=e.currentTarget.classList.contains('minute-hand');const move=ev=>{const a=clockAngle(ev);if(minute)handTime.m=Math.round(a/30)*5%60;else handTime.h=Math.max(1,Math.min(12,Math.round((a-handTime.m*.5)/30)||12));drawClock(handTime)},stop=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop)}
function pickMinute(e){if(e.target.classList.contains('hand')||e.target.classList.contains('number'))return;handTime.m=Math.round(clockAngle(e)/30)*5%60;drawClock(handTime)}
function time12(t){const period=t.h<12?'上午':'下午';let h=t.h%12;if(h===0)h=12;return {period,h,m:t.m}}
function durationText(min){return `${Math.floor(min/60)}小时${pad(min%60)}分钟`}
function loadConvert(){const direction=Math.random()<.5?'to24':'to12';current={...current,direction};const simple=time12(current);const shown=direction==='to24'?`${simple.period} ${format({h:simple.h,m:simple.m})}`:format(current);$('#questionTitle').textContent=direction==='to24'?`请把 ${shown} 换成 24 小时制`:`请把 ${shown} 换成 12 小时制`;$('#convertHint').textContent=direction==='to24'?'请输入 24 小时制时间':'请输入 12 小时制时间，并选择上午或下午';$('#periodRow').classList.toggle('hidden',direction==='to24');chosenPeriod='上午';document.querySelectorAll('.period').forEach(x=>x.classList.toggle('active',x.dataset.period==='上午'));$('#convertHour').value='';$('#convertMinute').value=''}
function miniClock(t){const hour=(t.h%12)*30+t.m*.5,minute=t.m*6;const hand=(a,len,w,color)=>{const r=a*Math.PI/180;return `<line x1="50" y1="50" x2="${(50+Math.sin(r)*len).toFixed(1)}" y2="${(50-Math.cos(r)*len).toFixed(1)}" stroke="${color}" stroke-width="${w}" stroke-linecap="round"/>`};const numbers=Array.from({length:12},(_,i)=>{const n=i+1,a=n*30*Math.PI/180;return `<text x="${(50+35*Math.sin(a)).toFixed(1)}" y="${(50-35*Math.cos(a)+3).toFixed(1)}" text-anchor="middle">${n}</text>`}).join('');return `<svg viewBox="0 0 100 100" aria-label="时钟"><circle cx="50" cy="50" r="45" fill="#fffaf1" stroke="#27344f" stroke-width="4"/>${numbers}${hand(hour,25,5,'#27344f')}${hand(minute,34,3,'#3867f5')}<circle cx="50" cy="50" r="4" fill="#ffb53d"/></svg>`}
function loadCalc(){$('#questionTitle').textContent='小火车从起点开到终点，一共用了多少分钟？';$('#calcClockA').innerHTML=miniClock(current.start);$('#calcClockB').innerHTML=miniClock(current.end);['#calcEndHour','#calcEndMinute','#calcStartHour','#calcStartMinute','#calcMinutes'].forEach(id=>$(id).value='')}
function load(){current=group[question];handTime=mode==='set'?{h:12,m:0}:{...current};groupComplete=false;const noClock=mode==='calc'||mode==='convert';$('#clockWrap').classList.toggle('hidden',noClock);if(!noClock)drawClock(mode==='read'?current:handTime);if(mode==='set')$('#targetTime').textContent=format(current);if(mode==='convert')loadConvert();if(mode==='calc')loadCalc();$('#progressText').textContent=`${question+1} / 5`;$('#progressBar').style.width=`${(question+1)*20}%`;feedback.textContent='';feedback.className='feedback';$('#hourInput').value='';$('#minuteInput').value=''}
function isCorrect(){if(mode==='read')return Number($('#hourInput').value)===current.h&&Number($('#minuteInput').value)===current.m;if(mode==='set')return handTime.h===current.h&&handTime.m===current.m;if(mode==='convert'){const h=Number($('#convertHour').value),m=Number($('#convertMinute').value);if(current.direction==='to24')return h===current.h&&m===current.m;const answer=time12(current);return h===answer.h&&m===answer.m&&chosenPeriod===answer.period}return Number($('#calcEndHour').value)===current.end.h&&Number($('#calcEndMinute').value)===current.end.m&&Number($('#calcStartHour').value)===current.start.h&&Number($('#calcStartMinute').value)===current.start.m&&Number($('#calcMinutes').value)===current.answer}
function answerText(){if(mode==='convert')return current.direction==='to24'?format(current):`${time12(current).period} ${format(time12(current))}`;if(mode==='calc')return `${format(current.end)} − ${format(current.start)} = ${current.answer} 分钟`;return format(current)}
function finish(correct){if(correct){score++;streak++;feedback.textContent='答对啦！你真是钟表小达人 🎉';feedback.className='feedback good'}else{streak=0;feedback.textContent=`再想一想，正确答案是 ${answerText()}`;feedback.className='feedback bad'}$('#streakCount').textContent=streak;submitBtn.disabled=true;setTimeout(()=>{if(question===4){groupComplete=true;submitBtn.disabled=false;feedback.textContent=`本组完成！答对 ${score} / 5 题，太棒了！`;return}question++;submitBtn.disabled=false;load()},1000)}
function selectMode(next){mode=next;question=0;score=0;makeGroup();document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));$('#modeTag').textContent=mode==='read'?'看钟写时间':mode==='set'?'拨钟调时间':mode==='convert'?'12 / 24 小时制':'时间竖式计算';$('#questionTitle').textContent=mode==='read'?'现在是几点钟？':mode==='set'?'请把钟拨到目标时间':'请计算时间';$('#readAnswer').classList.toggle('hidden',mode!=='read');$('#setAnswer').classList.toggle('hidden',mode!=='set');$('#convertAnswer').classList.toggle('hidden',mode!=='convert');$('#calcAnswer').classList.toggle('hidden',mode!=='calc');load()}
submitBtn.addEventListener('click',()=>{if(!groupComplete)finish(isCorrect())});
document.querySelectorAll('.mode').forEach(btn=>btn.addEventListener('click',()=>selectMode(btn.dataset.mode)));
document.querySelectorAll('.period').forEach(btn=>btn.addEventListener('click',()=>{chosenPeriod=btn.dataset.period;document.querySelectorAll('.period').forEach(x=>x.classList.toggle('active',x===btn))}));
$('#restartBtn').addEventListener('click',()=>{question=0;score=0;streak=0;$('#streakCount').textContent=0;makeGroup();load()});
makeGroup();load();
